name: note-server build
# 触发workflow的条件
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 5m
          script: |
            cd /home/note-server
            git pull
            yarn restart
